name       : nnn
version    : '4.6'
release    : 28
source     :
    - https://github.com/jarun/nnn/archive/refs/tags/v4.6.tar.gz : 15acaf9a88cfb5a2a640d3ef55a48af644fba92b46aac0768efe94c4addf7e3f
license    : BSD-2-Clause
component  : system.utils
summary    : A simple console file manager forked from Noice.
description: |
    A simple console file manager forked from Noice.
builddeps  :
    - pkgconfig(ncursesw)
rundeps    :
    - atool
    - libarchive
    - mediainfo
    - moreutils
    - rclone
    - sshfs-fuse
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
