name       : nnn
version    : '4.0'
release    : 19
source     :
    - https://github.com/jarun/nnn/releases/download/v4.0/nnn-v4.0.tar.gz : a219ec8fad3dd0512aadae5840176f3265188c4c22da3b17b133bac602b40754
license    : BSD-2-Clause
component  : system.utils
summary    : A simple console file manager forked from Noice.
description: |
    A simple console file manager forked from Noice.
builddeps  :
    - pkgconfig(ncursesw)
rundeps    :
    - atool
    - libarchive
    - mediainfo
    - moreutils
    - rclone
    - sshfs-fuse
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
