name       : nnn
version    : '3.3'
release    : 15
source     :
    - https://github.com/jarun/nnn/releases/download/v3.3/nnn-v3.3.tar.gz : 16b245cf984d81a7e35f1a6a6f52bede4810784f06074d69369f664efdf32aca
license    : BSD-2-Clause
component  : system.utils
summary    : A simple console file manager forked from Noice.
description: |
    A simple console file console file manager forked from Noice.
builddeps  :
    - pkgconfig(ncursesw)
rundeps    :
    - atool
    - libarchive
    - mediainfo
    - moreutils
    - rclone
    - sshfs-fuse
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
