name       : nnn
version    : '4.3'
release    : 23
source     :
    - https://github.com/jarun/nnn/releases/download/v4.3/nnn-v4.3.tar.gz : b6df8e262e5613dd192bac610a6da711306627d56573f1a770a173ef078953bb
license    : BSD-2-Clause
component  : system.utils
summary    : A simple console file manager forked from Noice.
description: |
    A simple console file manager forked from Noice.
builddeps  :
    - pkgconfig(ncursesw)
rundeps    :
    - atool
    - libarchive
    - mediainfo
    - moreutils
    - rclone
    - sshfs-fuse
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
