name       : nnn
version    : 3.6
release    : 18
source     :
    - https://github.com/jarun/nnn/releases/download/v3.6/nnn-v3.6.tar.gz : 875094caebcc22ecf53b3722d139b127d25e1d5563a954342f32ded8980978b5
license    : BSD-2-Clause
component  : system.utils
summary    : A simple console file manager forked from Noice.
description: |
    A simple console file manager forked from Noice.
builddeps  :
    - pkgconfig(ncursesw)
rundeps    :
    - atool
    - libarchive
    - mediainfo
    - moreutils
    - rclone
    - sshfs-fuse
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
