name       : nnn
version    : '2.3'
release    : 4
source     :
    - https://github.com/jarun/nnn/archive/v2.3.tar.gz : eaad2ccf0d781aeeb38fdfc4ad75a0405ca3da4f82ded64cce766a74a2b299ab
license    : BSD-2-Clause
component  : system.utils
summary    : A simple console file manager forked from Noice.
description: |
    A simple console file console file manager forked from Noice.
builddeps  :
    - pkgconfig(ncursesw)
rundeps    :
    - atool
    - mediainfo
    - moreutils
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
