name       : nnn
version    : '2.4'
release    : 5
source     :
    - https://github.com/jarun/nnn/archive/v2.4.tar.gz : 859ba5bd4892016aed9a4830ee1e1b03eb74e94c4f1bd82f0288dc559f7327eb
license    : BSD-2-Clause
component  : system.utils
summary    : A simple console file manager forked from Noice.
description: |
    A simple console file console file manager forked from Noice.
builddeps  :
    - pkgconfig(ncursesw)
rundeps    :
    - atool
    - mediainfo
    - moreutils
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
