name       : nnn
version    : '2.7'
release    : 8
source     :
    - https://github.com/jarun/nnn/releases/download/v2.7/nnn-v2.7.tar.gz : e5ed218fcf5b92316f1f509dbe663b961d2a2a7629e982124379e8c3630870f3
license    : BSD-2-Clause
component  : system.utils
summary    : A simple console file manager forked from Noice.
description: |
    A simple console file console file manager forked from Noice.
builddeps  :
    - pkgconfig(ncursesw)
rundeps    :
    - atool
    - mediainfo
    - moreutils
    - sshfs-fuse
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
