name       : nnn
version    : '4.4'
release    : 24
source     :
    - https://github.com/jarun/nnn/releases/download/v4.4/nnn-v4.4.tar.gz : e04a3f0f0c2af1e18cb6f005d18267c7703644274d21bb93f03b30e4fd3d1653
license    : BSD-2-Clause
component  : system.utils
summary    : A simple console file manager forked from Noice.
description: |
    A simple console file manager forked from Noice.
builddeps  :
    - pkgconfig(ncursesw)
rundeps    :
    - atool
    - libarchive
    - mediainfo
    - moreutils
    - rclone
    - sshfs-fuse
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
