name       : nnn
version    : '4.5'
release    : 27
source     :
    - https://github.com/jarun/nnn/archive/refs/tags/v4.5.tar.gz : fadc15bd6d4400c06e5ccc47845b42e60774f368570e475bd882767ee18749aa
license    : BSD-2-Clause
component  : system.utils
summary    : A simple console file manager forked from Noice.
description: |
    A simple console file manager forked from Noice.
builddeps  :
    - pkgconfig(ncursesw)
rundeps    :
    - atool
    - libarchive
    - mediainfo
    - moreutils
    - rclone
    - sshfs-fuse
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
