name       : nnn
version    : '2.5'
release    : 6
source     :
    - https://github.com/jarun/nnn/archive/v2.5.tar.gz : 3636f172a024de5c12420a80dbe3d006d42b5e0a17e70a527963c864af22655c
license    : BSD-2-Clause
component  : system.utils
summary    : A simple console file manager forked from Noice.
description: |
    A simple console file console file manager forked from Noice.
builddeps  :
    - pkgconfig(ncursesw)
rundeps    :
    - atool
    - mediainfo
    - moreutils
    - sshfs-fuse
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
