name       : nnn
version    : '2.2'
release    : 2
source     :
    - https://github.com/jarun/nnn/archive/v2.2.tar.gz : 88dd08d624ae7a61ef749b1e258e4b29ed61ba9fcc5a18813f291ce80efc5e74
license    : BSD-2-Clause
component  : system.utils
summary    : A simple console file manager forked from Noice.
description: |
    A simple console file console file manager forked from Noice.
builddeps  :
    - pkgconfig(ncursesw)
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
